#! /bin/bash

# If there's a config file we'll source it
. ${0%/*}/botii.conf \
  || echo "Info: No config file found, continuing with default settings!"

# Default values, if not set in the config file these are used
: "${nickname:=botii}"
: "${fullname:=bot built on ii - https://github.com/iamtew/botii}"
: "${server:=irc.freenode.net}"
: "${port:=6667}"
: "${channels:=#botii}"
: "${system_user:=botii}"
: "${ircdir:=/tmp/botii}"

# Some other files we need
pidfile="${ircdir}/pid"
tformat="%F_%T"

trap botii_stop INT # CTRL-C Murder Everything
trap 'kill 0' EXIT  # Kill everything unclean exit (should respawn)

# Check we're running as correct user
if [[ "$USER" != "$system_user" ]] ; then
  echo "Error: Running as user '${USER}', Expected user '${system_user}'"
  exit 1
fi

if [[ -d "$ircdir" ]] ; then
  echo "Error: IRC directory exits, is bot already running?"
  exit 1
fi

mkdir -p -m 0700 "$ircdir"

# Functions
botii_start() {
  echo "$(date +"$tformat") Starting botii"
  ii -i "$ircdir" -s "$server" -p "$port" -n "$nickname" -f "$fullname" &
  IIPID=$!
  echo -n "$IIPID" > "$pidfile"
  return 0
}

botii_stop() {
  echo "$(date +"$tformat") Stopping botti"
  rm -rf "$ircdir"
  kill 0
  exit 0
}

join_channels() {
  # Wait for the connection
  echo "$(date +"$tformat") Waiting for '$server' to be available"
  while ! test -p "${ircdir}/${server}/in" ; do echo -n '.' ; sleep 1 ; done

  for channel in $channels ; do
    echo "$(date +"$tformat") Joining channel: ${channel}"
    echo "/JOIN ${channel}" > "${ircdir}/${server}/in"

    # Wait until the channel is available
    while ! test -p "${ircdir}/${server}/${channel}/in" ; do echo -n '.' ; sleep 1 ; done
    echo "$(date +"$tformat") Starting watcher: ${channel}"
    exec ${0%/*}/botii_watch "$ircdir" "$server" "$nickname" "$channel" &
  done
}


botii_start
join_channels &

echo "$(date +"$tformat")  botii successfully launched, PID $IIPID"

if [[ -z $IIPID ]] ; then
  echo "\$IIPID variable empty, this shouldn't even happen!"
  exit 1
else
  wait $IIPID
  kill 0
fi

exit 1
